development:
  logging_enabled: true
  logger_class: LoggedException 
  notification_address: 
  notification_sender: noreply@example.com 
  notification_threshold: 10
test:
  logging_enabled: false
  logger_class: LoggedException 
  notification_address: 
  notification_sender: noreply@example.com 
  notification_threshold: 10
production:
  logging_enabled: true
  logger_class: LoggedException
  notification_address: 
  notification_sender: noreply@example.com 
  notification_threshold: 10
