development:
  logging_enabled: true
  logger_class: <%= class_name %> 
test:
  logging_enabled: false
  logger_class: <%= class_name %> 
production:
  logging_enabled: true
  logger_class: <%= class_name %> 
